version: "3"

services:
  website:
    container_name: "RamblingGeekDemo"
    build:
      context: .
      dockerfile: Website/Dockerfile
    ports:
      - 4004:80
      - 4005:443
    environment:
      RamblingGeekStreamURL: "${RamblingGeekStreamURL}"